services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ideaboard?schema=public
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .
          target: /app
          action: sync
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ideaboard
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:


